### ISSUE TITLE
Link to documentation in README.md leads to empty page

### ISSUE THREAD

**Issue by sustmi** [sonata-project/form-extensions#229]
## Steps to reproduce
1. Open [`README.md`](https://github.com/sonata-project/sonata-doctrine-extensions/blob/1.x/README.md)
2. Go to the "official website" link in "Documentation" section (currently: https://sonata-project.org/bundles/form-extensions)

## Expected results
Documentation of SonataFormExtensions bundle should be shown.

## Actual results
An empty page is shown:
![image](https://user-images.githubusercontent.com/885946/118694078-3479bd80-b7fb-11eb-879a-605d6e871d52.png)

**Comment by OskarStark** [comment]
@core23 @rande what do we need to do to get it shown?

**Comment by core23** [comment]
There is an open issue for this: https://github.com/sonata-project/dev-kit/issues/879

AFAIK we did not update the sonata-project.org code for a while...

**Comment by OskarStark** [comment]
You mean this one?
https://github.com/sonata-project/sonata-project.org

**Comment by core23** [comment]
> You mean this one?
> https://github.com/sonata-project/sonata-project.org

Still no permissions :(

**Comment by VincentLanglet** [comment]
Fixed ; the new link is https://docs.sonata-project.org/projects/form-extensions/en/1.x/
