### ISSUE TITLE
Deprecate passing an array as argument 1 to `ErrorElement::addValidation`

### ISSUE THREAD

**Issue by franmomu** [sonata-project/form-extensions#358]
## Feature Request

We can deprecate passing an array and change the parameter type to `string` in 2.0.

https://github.com/sonata-project/form-extensions/blob/50979010b90ebbec3d33f00b923dd0d5ec15eb11/src/Validator/ErrorElement.php#L195-L208

**Comment by VincentLanglet** [comment]
Let's do this before the 2.0 version then
