### ISSUE TITLE
The EqualType form should be deprecated in favor of SonataAdmin/EqualOperatorType

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/form-extensions#67]
https://github.com/sonata-project/form-extensions/blob/1.x/src/Type/EqualType.php

I need to check again but I think that the EqualType is only used for filters.
It's used in SonataAdmin and SonataDoctrineORM.

Since it's only for the operator of the filter, it makes more sens to
- Deprecate the EqualType
- use the new EqualOperatorType in these admin instead of the EqualType.
- Remove the EqualType in the next major

See.
https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Form/Type/Operator/EqualOperatorType.php

WDYT @greg0ire ? @core23 ? @phansys :)

**Comment by greg0ire** [comment]
Are there other types like that one, that could be removed?

**Comment by VincentLanglet** [comment]
@greg0ire  In order the form to be related to filter, he has to export const.

The only other one in this situation is the BooleanType.
https://github.com/sonata-project/form-extensions/blob/1.x/src/Type/BooleanType.php

And it's indeed filter-related.
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/search?q=BooleanType&unscoped_q=BooleanType

But actually, there is no booleanType in the SonataAdmin so this can't be deprecated.
It could make sens to create a type in sonataAdmin and deprecate this one.

**Comment by VincentLanglet** [comment]
The PR is created https://github.com/sonata-project/form-extensions/pull/68/files

For the BooleanType, since it's filter-related, I propose to:
- Create a BooleanType in SonataAdmin\Form\Type\Filter
- Deprecate this one.

**Comment by greg0ire** [comment]
> Do you agree ?

I suppose I do… I have no clue why it's better in one package or in the other to be honest. @core23 @phansys , maybe you do?

**Comment by phansys** [comment]
I don't know if there is a plan to move form types from one package to another. At least, I don't see any related task in our [Next majors](https://github.com/orgs/sonata-project/projects/1) project.
Currently, the only Sonata package depending on this one seems to be [block-bundle](https://github.com/sonata-project/form-extensions/network/dependents?package_id=UGFja2FnZS01NDMwNTkwMDk%3D).
I think we should make clear that point before going ahead with this decision. 
Additionally, note that the [documentation](https://sonata-project.org/bundles/form-extensions) for this package is currently empty.

**Comment by core23** [comment]
I'm not sure if we should move it or not. The current solution is okay for now and this is not the biggest task we have to face at the moment.

**Comment by VincentLanglet** [comment]
It depends on the goal of this repository.

IMHO it should only export reusable, context-free form, which are potentially used in multiple Sonata package. 

A form like a the boolean one with a context (only used for filters) and used by a single package (sonata/admin) is better directly in the specific package. As A User, If I want to look for every available filter, I will check in the sonata admin package ; I won't check in BOTH the sonata admin package and this project.

> The current solution is okay for now and this is not the biggest task we have to face at the moment.

I understand it's not the biggest priority of core maintainers, but if It's an improvement you agree with I have time to do it.

**Comment by VincentLanglet** [comment]
After some personal reflexion, the BooleanType should stay here.
The BooleanType instead of the EqualType, is a fieldType.
And it is not 100% filter related. It can be used somewhere else.
It's a context free Form, like the ChoiceType or the HiddenType provided by symfony.
